---
- hosts: "{{ host_groups }}"
  gather_facts: true
  remote_user: "{{ user }}"
  become: yes

  vars:
    packages:
      - python-pip
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    docker_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
    local_repo_file_path: /etc/yum.repos.d/docer-ce.repo

  pre_tasks:
    - name: 'install python'
      # The epel-release is for installing python-pip on CentoOS 7
      raw: 'sudo yum install -y python epel-release'

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes

    - name: Add Docker repo
      get_url:
        url: "{{ docker_repo_url }}"
        dest: "{{ local_repo_file_path }}"
      become: yes

    - name: Install the latest version of docker-ce docker-ce-cli containerd.io
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      become: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes