- hosts: provisioner
  connection: local
  vars:
    region: us-east-2
  vars_files:
    - aws_pass.yml
  tasks:
    - name: Gather EC2 facts
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:type": "webserver"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      loop: "{{ ec2.instances }}"