---
- hosts: "{{ host_groups }}"
  gather_facts: true
  remote_user: "{{ user }}"
  become: yes

  vars:
    package: iptables-services

  tasks:
    - name: Install iptables-services
      yum:
        name: "{{ package }}"
        state: latest
        update_cache: yes

    - name: Update iptables for port 22, 80, 443
      shell: |
        systemctl enable iptables

        # Stop the standard brute force SSH attacks by dropping connections
        # if the hit count (failed attempts) hits four and it slows it to 60 seconds
        iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent --set
        iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 -j DROP

        # Allow HTTP port 80/443 and 22 into your system.
        iptables -A INPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
        iptables -A OUTPUT -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT
        iptables -A INPUT -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
        iptables -A OUTPUT -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT

        # Allows already connected to keep going using conntrack:
        iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

        # Allow the services on the host to talk to each other.
        iptables -A INPUT -i lo -j ACCEPT

        # Save firewall rules to /etc/sysconfig/iptables
        service iptables save